project:
  type: website
  output-dir: docs

website:
  title: "GEOspatial Tutorials"
  navbar:
    background: light
    foreground: dark
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: arcgispro.qmd
        text: ArcGIS Pro
      - href: qgis.qmd
        text: QGIS
      - href: rstudio.qmd
        text: R
    right:  
      - icon: envelope-at
        href: mailto:garrettsmith@arizona.edu

format:
  html:
    theme: flatty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

